config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :game_tags
  devise_for :users
  resources :games
 get "/" => "application#home"
 get "/aboutus" => "application#aboutus"
 get "/login" => "application#login"
 get "/suggestions" => "application#suggestions"
   root to: "application#home"
end

app/models/game.rb
class Game < ActiveRecord::Base
  def short_caption
    return caption[0..250] + "..."
  end

  def spaced_name
   spacename = ""
   name.split("").each do |letter|
     spacename <<  letter
     spacename <<  " "
    end
    return spacename.upcase
  end
end

app/models/game_tag.rb
class GameTag < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


def home
@game=Game.find_by(:name => "Agar.io")
end








end

app/controllers/game_tags_controller.rb
class GameTagsController < ApplicationController
  before_action :set_game_tag, only: [:show, :edit, :update, :destroy]

  # GET /game_tags
  # GET /game_tags.json
  def index
    @game_tags = GameTag.all
  end

  # GET /game_tags/1
  # GET /game_tags/1.json
  def show
  end

  # GET /game_tags/new
  def new
    @game_tag = GameTag.new
  end

  # GET /game_tags/1/edit
  def edit
  end

  # POST /game_tags
  # POST /game_tags.json
  def create
    @game_tag = GameTag.new(game_tag_params)

    respond_to do |format|
      if @game_tag.save
        format.html { redirect_to @game_tag, notice: 'Game tag was successfully created.' }
        format.json { render :show, status: :created, location: @game_tag }
      else
        format.html { render :new }
        format.json { render json: @game_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_tags/1
  # PATCH/PUT /game_tags/1.json
  def update
    respond_to do |format|
      if @game_tag.update(game_tag_params)
        format.html { redirect_to @game_tag, notice: 'Game tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_tag }
      else
        format.html { render :edit }
        format.json { render json: @game_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_tags/1
  # DELETE /game_tags/1.json
  def destroy
    @game_tag.destroy
    respond_to do |format|
      format.html { redirect_to game_tags_url, notice: 'Game tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_tag
      @game_tag = GameTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_tag_params
      params.require(:game_tag).permit(:game_id, :tag_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    if params[:search].present?
      @games = Game.where("lower(name) LIKE ?", "%#{params[:search].downcase}%")
    else
      @games = Game.all
    end
  end


  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :caption, :summary, :pic, :link, :editors_choice)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_tags_helper.rb
module GameTagsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/application/aboutus.html.erb
<h1>About Us</h1>

app/views/application/home.html.erb
  <div class="container">



    <div id="editors-choice-carousel" class="owl-carousel">

<%Game.where(:editors_choice => true).each do |game|%>
    <div class="editors-choice">
      <img src="<%= game.pic%>">
      <h3>Editor's Choice</h3>
      <a href="<%= game.link%>" class="play-now" target="_blank">Play it NOW!</a>
      <h4 class="editors-choice-caption"><%= game.short_caption%></h4>
    </div>
    <% end -%>
      <!-- <div>  </div>
      <div>  </div>
      <div>  </div>
      <div>  </div>
      <div>  </div>
      <div>  </div> -->

    </div>
    <script type="text/javascript">$(document).ready(function() {

      $("#editors-choice-carousel").owlCarousel({
        autoPlay: true,
        singleItem: true,
        stopOnHover: true,


      });

    });</script>


    <!-- <i class="fa fa-spinner fa-pulse"></i> -->

    <br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <p>©2016</p>



  </div>

app/views/application/login.html.erb
<div class="login-background">
  <div class="container">
    <div class="login-page-body">
      <h1>Login</h1>

      <form action="" class="loginform">
        <input name="username" placeholder="   →Username←">
        <br>
        <input name="password" placeholder="   →Password←">

      </form>
    </div>
  </div>
</div>

app/views/application/suggestions.html.erb
<h1>Suggestions</h1>

app/views/game_tags/_form.html.erb
<%= form_for(@game_tag) do |f| %>
  <% if @game_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_tag.errors.count, "error") %> prohibited this game_tag from being saved:</h2>

      <ul>
      <% @game_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_tags/edit.html.erb
<h1>Editing Game Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_tag %> |
<%= link_to 'Back', game_tags_path %>

app/views/game_tags/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<!-- delete this ^ -->


<p id="notice"><%= notice %></p>

<h1>Listing Game Tags</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_tags.each do |game_tag| %>
      <tr>
        <td><%= game_tag.game_id %></td>
        <td><%= game_tag.tag_id %></td>
        <td><%= link_to 'Show', game_tag %></td>
        <td><%= link_to 'Edit', edit_game_tag_path(game_tag) %></td>
        <td><%= link_to 'Destroy', game_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game tag', new_game_tag_path %>

app/views/game_tags/new.html.erb
<h1>New Game Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', game_tags_path %>

app/views/game_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @game_tag.game_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @game_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_game_tag_path(@game_tag) %> |
<%= link_to 'Back', game_tags_path %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :pic %><br>
    <%= f.text_field :pic %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
      <div class="field">
    <%= f.label :tutorial %><br>
    <%= f.text_area :tutorial %>
  </div>
  <div class="field">
    <%= f.label :videolink %><br>
    <%= f.text_field :videolink %>
  </div>
    <div class="field">
    <%= f.label :editors_choice %><br>
    <%= f.check_box :editors_choice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> 

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %> |
<%= link_to 'Destroy', game_path(@game), :method => :delete %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="games-title">G A M E S</h1>
<hr>
<div class="editors-choice-games">
  <% @games.each do |game|%>
  <%#Game.where(:editors_choice => true).each do |game|%>
  <a href="/games/<%=game.id%>">
    <div class="game-list-item">

      <div class="img-container">

        <img src="<%= game.pic%>">
        <% if game.editors_choice == true%>
        <h3 class="tiny-banner">Editor's Choice</h3>
        <%end%>

        <div class="title-game" ><%= game.name%></div>
      </div>

      <h4 class="editors-choice-caption-games"><%= game.caption%></h4>
    </div>
  </a>
  <% end %>







<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Caption</th>
      <th>Summary</th>
      <th>Pic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.caption %></td>
        <td><%= game.summary %></td>
        <td><%= game.pic %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %> -->
 <!--  </tbody>
</table> -->

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<h1 class="games-title-show"><%= @game.spaced_name %></h1>

<div class="pic-games-show"><img src="<%= @game.pic%>">
</div>






<div class="games-show-caption"><p>
  <%= @game.caption %>
</p></div>

<p>
  <strong>Summary:</strong>
  <%= @game.summary %>
</p>

<p>
  <strong>Pic:</strong>
  <%= @game.pic %>
</p>

<p>
  <strong>Link:</strong>
  <%= @game.link %>
</p>


<% if current_user.present? && current_user.admin == true  %>
  <%= link_to 'Edit', edit_game_path(@game) %> |
  <% end %>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>What2Play</title>
  <link href='https://fonts.googleapis.com/css?family=Inconsolata' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.css">
<link href='https://fonts.googleapis.com/css?family=Coming+Soon' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.js"type="text/javascript"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
<a href="#" class="navlink triple-line"><i class="fa fa-bars" aria-hidden="true"></i></a>
  <span class="home-button"><a href="/" class="navlink">
    <%= image_tag('logo.png') %>
  </a> </span>
  <a href="/suggestions" class="navlink"> SUGGESTIONS</a>
  <a href="/games" class="navlink"> TUTORIALS</a>
  <a href="" class="navlink"> ABOUT US</a>

  <a href="" class="search navlink">
    <i class="fa fa-search"> </i>   </a>

    <form action="<%= games_path %>" class="navlink">
      <input name="search" placeholder="CAN'T FIND YOUR FAV GAME? ">

    </form>
    <div class="login">


      <%if current_user.present?%>
      <a data-method="delete" href="/users/sign_out" class="navlink"> SIGN OUT</a>
      <a href="/users/edit" class="navlink navprofile"><%= current_user.email %></a>
      <%else %>
      <a href="/users/sign_in" class="navlink"> LOGIN</a>
      <a href="/users/sign_up" class="navlink"> SIGN UP</a>
      <% end %>


 </div>


<div class="drop-down-container">
  <div class="drop-down"> <a href="/suggestions"> SUGGESTIONS</a>
  </div>
<div class="drop-down"> <a href="/games"> TUTORIALS</a></div>
<div class="drop-down"> <a href="/games"> ABOUT US</a></div>
<div class="drop-down"> <a href="/games"> SEARCH</a>    </a>

    <form action="<%= games_path %>" class="drop-search">
      <input name="search" class="search-drop" placeholder="CAN'T FIND YOUR FAV GAME? ">

    </form></div>
<div class="drop-down"> <a href="/games"> LOGIN</a></div>
<div class="drop-down"> <a href="/games"> SIGN UP</a></div>

</div>




  </nav>




<!-- <br>
<br>
<br><br><br> -->

<% if notice.present?%>
       <p class="notice"><%= notice %></p>
<% end%>
<% if alert.present?%>
       <p class="alert"><%= alert %></p>
<% end%>

<%= yield %>

<script type="text/javascript">
$('.triple-line').click(function(){
  if($('.drop-down-container').css('display')=='none'){
    $('.drop-down-container').slideDown();
  }
  else{
    $('.drop-down-container').slideUp();
  }

})</script>

















</body>
</html>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<!-- delete this ^ -->




<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>